#!/usr/bin/env bash

# sedi - Cross-platform helper for 'sed -i'
# Usage: sedi 's/foo/bar/g' filename
sedi() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i "" "$@"
  else
    sed -i "$@"
  fi
}
